---
# Setup/install tasks.
- name: Install python3-pip via package manager
  import_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- name: Install python3-pip via package manager
  import_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Install awscli via pip.
  pip:
    name: awscli
    version: "{{ awscli_version }}"
  become: yes

- name: Ensure the users' .aws directory exists.
  file:
    path: "~/.aws"
    state: directory
    owner: "{{ item.username }}"
    group: "{{ item.group | default(item.username) }}"
    mode: 0755
  become: yes
  become_user: "{{ item.username }}"
  loop: "{{ awscli_users }}"
  loop_control:
    label: "{{ item.username }}"

- name: Create the users' .aws/config file.
  template:
    src: aws_config.j2
    dest: "~/.aws/config"
    owner: "{{ item.username }}"
    group: "{{ item.group | default(item.username) }}"
    mode: 0600
  become: yes
  become_user: "{{ item.username }}"
  loop: "{{ awscli_users }}"
  loop_control:
    label: "{{ item.username }}"

- name: Create the users' .aws/credentials file.
  template:
    src: aws_credentials.j2
    dest: "~/.aws/credentials"
    owner: "{{ item.username }}"
    group: "{{ item.group | default(item.username) }}"
    mode: 0600
  become: yes
  become_user: "{{ item.username }}"
  loop: "{{ awscli_users }}"
  loop_control:
    label: "{{ item.username }}"
